In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
import numpy as np
import warnings 

from sklearn.preprocessing import LabelEncoder

warnings.filterwarnings("ignore")
ln = LabelEncoder()
nb_gau = GaussianNB()
nb_mul = MultinomialNB()

In [7]:
sal_data = pd.read_csv("SalaryData_Train.csv")

In [8]:
sal_data.isna().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [9]:
sal_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            30161 non-null  int64
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64
 10  capitalloss    30161 non-null  int64
 11  hoursperweek   30161 non-null  int64
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB

In [10]:
sal_data.head(2)

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K

In [11]:
sal_data.workclass = ln.fit_transform(sal_data.workclass)
sal_data.education = ln.fit_transform(sal_data.education)
sal_data.maritalstatus = ln.fit_transform(sal_data.maritalstatus)
sal_data.occupation = ln.fit_transform(sal_data.occupation)
sal_data.relationship = ln.fit_transform(sal_data.relationship)
sal_data.race = ln.fit_transform(sal_data.race)
sal_data.sex = ln.fit_transform(sal_data.sex)
sal_data.native = ln.fit_transform(sal_data.native)
sal_data.Salary = ln.fit_transform(sal_data.Salary)

In [17]:
sal_data.head(2)

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,5,9,13,4,0,1,4,1,2174,0,40,37,0
1,50,4,9,13,2,3,0,4,1,0,0,13,37,0

In [19]:
x = sal_data.drop(labels="Salary",axis=1)
y = sal_data[["Salary"]]

### Gaussia NB

In [71]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=12,test_size=0.20,stratify=y)
y_train_pred = nb_gau.fit(x_train,y_train).predict(x_train)
print("===========Train Data================")
print("Accurecy Score    ",accuracy_score(y_train,y_train_pred))

print("")
print("===========Test Data================")
y_test_pred = nb_gau.fit(x_train,y_train).predict(x_test)
print("Accurecy Score",accuracy_score(y_test,y_test_pred))

===========Train Data================
Accurecy Score     0.7927456839309429

===========Test Data================
Accurecy Score 0.797808764940239

##  For MultinomialNB

In [84]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=12,test_size=0.20,stratify=y)
y_train_pred = nb_mul.fit(x_train,y_train).predict(x_train)
print("===========Train Data================")
print("Accurecy Score    ",accuracy_score(y_train,y_train_pred))

print("")
print("===========Test Data================")
y_test_pred = nb_gau.fit(x_train,y_train).predict(x_test)
print("Accurecy Score",accuracy_score(y_test,y_test_pred))

===========Train Data================
Accurecy Score     0.7741533864541833

===========Test Data================
Accurecy Score 0.797808764940239

## For Test Data

In [54]:
sal_test=pd.read_csv("SalaryData_Test.csv")

In [55]:
sal_test

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15055,33,Private,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,<=50K
15056,39,Private,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K
15057,38,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
15058,44,Private,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K
15059,35,Self-emp-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K

In [56]:
sal_test.workclass = ln.fit_transform(sal_test.workclass)
sal_test.education = ln.fit_transform(sal_test.education)
sal_test.maritalstatus = ln.fit_transform(sal_test.maritalstatus)
sal_test.occupation = ln.fit_transform(sal_test.occupation)
sal_test.relationship = ln.fit_transform(sal_test.relationship)
sal_test.race = ln.fit_transform(sal_test.race)
sal_test.sex = ln.fit_transform(sal_test.sex)
sal_test.native = ln.fit_transform(sal_test.native)
sal_test.Salary = ln.fit_transform(sal_test.Salary)

In [57]:
sal_test

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,2,1,7,4,6,3,2,1,0,0,40,37,0
1,38,2,11,9,2,4,0,4,1,0,0,50,37,0
2,28,1,7,12,2,10,0,4,1,0,0,40,37,1
3,44,2,15,10,2,6,0,2,1,7688,0,40,37,1
4,34,2,0,6,4,7,1,4,1,0,0,30,37,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15055,33,2,9,13,4,9,3,4,1,0,0,40,37,0
15056,39,2,9,13,0,9,1,4,0,0,0,36,37,0
15057,38,2,9,13,2,9,0,4,1,0,0,50,37,0
15058,44,2,9,13,0,0,3,1,1,5455,0,40,37,0
15059,35,3,9,13,2,3,0,4,1,0,0,60,37,1

In [58]:
x = sal_test.drop(labels="Salary",axis=1)
y = sal_test[["Salary"]]

### Testing for Gaussian NB

In [87]:
x_pred = nb_gau.predict(x)
accuracy_score(x_pred,y)

0.7937583001328021

###  Testing For MultinomialNB

In [86]:
x_pred = nb_mul.predict(x)
accuracy_score(x_pred,y)

0.7749667994687915