In [1]:
import pandas as pd
import scipy.stats as stats
import numpy as np

## Cutlet Data

In [8]:
cut_data=pd.read_csv('Cutlets.csv')
cut_data.head()

   Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [9]:
from scipy.stats import ttest_ind

In [13]:
statistic,pvalue=ttest_ind(cut_data['Unit A'],cut_data['Unit B'])
print('statistics is {}\n pvalue is {}'.format(statistic,pvalue))
if pvalue<0.05:
    print('\nSignificant difference in diameter of the cutlet (Ha)')
else:
    print('\nNo Significant change in diameter of the cutlet (Ho)')

statistics is 0.7228688704678063
 pvalue is 0.4722394724599501

No Significant change in diameter of the cutlet (Ho)

###  For Lab Data

In [6]:
lab_data=pd.read_csv('LabTAT.csv')
lab_data

     Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [14]:
statistic,pvalue=stats.f_oneway(lab_data['Laboratory 1'],lab_data['Laboratory 2'],lab_data['Laboratory 3'],lab_data['Laboratory 4'])

print('statistics is {}\npvalue is {}'.format(statistic,pvalue))
if pvalue<0.05:
    print('There is significant difference in average TAT of reports between the laboratories (Ha)')
else:
    print('There is no significant change in verage TAT of reports between the laboratories (Ho)')

statistics is 118.70421654401437
pvalue is 2.1156708949992414e-57
There is significant difference in average TAT of reports between the laboratories (Ha)

## Buyer Data

In [19]:
data=pd.read_csv('BuyerRatio (1).csv')
data

  Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [20]:
from scipy.stats import chi2_contingency

In [22]:
data=[[50,435],[142,1523],[131,1356],[70,750]]
from scipy.stats import chi2_contingency
chi2_contingency(data)

print(pvalue)
if pvalue<0.05:
    print('There is significant change in proportion between male and female (Ha)')
else:
    print('There is no significant change in proportion between male and female (Ho)')

2.1156708949992414e-57
There is significant change in proportion between male and female (Ha)

### Customer data

In [23]:
order_data=pd.read_csv('Costomer+OrderForm.csv')
order_data

    Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [24]:
values=[[271,29],[267,33],[269,31],[280,20]]

In [25]:
chi2_contingency(values)

print(pvalue)
if pvalue<0.05:
    print('There is significant change in proportion (Ha)')
else:
    print('There is no significant change in proportion (Ho)')

2.1156708949992414e-57
There is significant change in proportion (Ha)