In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("book (1).csv")

In [4]:
data

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,1,0,0,1,1,1,0,1,1
1996,0,0,0,0,0,0,0,0,0,0,0
1997,0,0,0,0,0,0,0,0,0,0,0
1998,0,0,1,0,0,0,0,0,0,0,0
1999,0,0,0,0,0,0,0,0,0,0,0

### Model Building

In [5]:
from mlxtend.frequent_patterns import apriori,association_rules

In [20]:
items = apriori(df = data,min_support=0.020,use_colnames=True)

In [21]:
items

     support                                           itemsets
0     0.4230                                         (ChildBks)
1     0.2475                                         (YouthBks)
2     0.4310                                          (CookBks)
3     0.2820                                         (DoItYBks)
4     0.2145                                           (RefBks)
..       ...                                                ...
271   0.0210  (RefBks, ChildBks, CookBks, ArtBks, DoItYBks, ...
272   0.0270  (RefBks, ChildBks, CookBks, GeogBks, DoItYBks,...
273   0.0310  (ChildBks, CookBks, ArtBks, GeogBks, DoItYBks,...
274   0.0225  (RefBks, ChildBks, CookBks, ArtBks, GeogBks, Y...
275   0.0240  (RefBks, ChildBks, CookBks, ArtBks, GeogBks, D...

[276 rows x 2 columns]

In [25]:
best_assoc = association_rules(df = items,min_threshold=0.91)
best_assoc

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(ItalCook),(CookBks),0.1135,0.4310,0.1135,1.000000,2.320186,0.064582,inf
1,(ItalAtlas),(RefBks),0.0370,0.2145,0.0370,1.000000,4.662005,0.029063,inf
2,(ItalArt),(ArtBks),0.0485,0.2410,0.0485,1.000000,4.149378,0.036812,inf
3,"(ItalCook, ChildBks)",(CookBks),0.0850,0.4310,0.0850,1.000000,2.320186,0.048365,inf
4,"(ChildBks, ItalAtlas)",(RefBks),0.0285,0.2145,0.0285,1.000000,4.662005,0.022387,inf
...,...,...,...,...,...,...,...,...,...
104,"(ItalArt, ArtBks, ItalCook, GeogBks)",(CookBks),0.0240,0.4310,0.0240,1.000000,2.320186,0.013656,inf
105,"(ItalArt, CookBks, GeogBks)","(ArtBks, ItalCook)",0.0250,0.0565,0.0240,0.960000,16.991150,0.022587,23.5875
106,"(ItalArt, ItalCook, GeogBks)","(ArtBks, CookBks)",0.0240,0.1670,0.0240,1.000000,5.988024,0.019992,inf
107,"(RefBks, CookBks, GeogBks, DoItYBks, YouthBks)",(ChildBks),0.0290,0.4230,0.0270,0.931034,2.201027,0.014733,8.3665
108,"(ChildBks, ArtBks, GeogBks, DoItYBks, YouthBks)",(CookBks),0.0335,0.4310,0.0310,0.925373,2.147037,0.016561,7.6246